const HeadMeta = () => {
  return (
    <>
      <title>Agora</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
    </>
  );
};

export default HeadMeta;
